### ISSUE TITLE
Prior art

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/10-accessible#1]
Please add links to others' guidelines to this issue

- https://user2021.r-project.org/participation/accessibility/
- https://www.w3.org/WAI/teach-advocate/accessible-presentations/
- https://www.techsmith.com/blog/how-to-create-alternative-text-for-images-for-accessibility-and-seo/
- https://www.wgbh.org/foundation/ncam/guidelines/guidelines-for-describing-stem-images
- http://diagramcenter.org/making-images-accessible.html
- http://diagramcenter.org/accessible-math-tools-tips-and-training.html
- https://www.csun.edu/universal-design-center/math-and-science-accessibility#A51
- https://www.writethedocs.org/videos/portland/2021/writing-documentation-with-neurodivergent-open-source-contributors-in-mind-rin-oliver/
- https://github.com/Chartability/POUR-CAF
- https://www.authorea.com/users/152134/articles/206076-making-scientific-content-more-accessible

**Comment by jooyoungseo** [comment]
* https://www.sigaccess.org/welcome-to-sigaccess/resources/describing-figures/

* https://sigchi.org/conferences/author-resources/accessibility-guide/

* https://www.sigaccess.org/welcome-to-sigaccess/resources/accessible-conference-guide/

* https://accessiblegraphs.org/?lang=en

* https://github.com/hasadna/accessible-graphs
* https://hassaku.github.io/DS-and-ML-with-screen-reader/

* https://github.com/hassaku/audio-plot-lib

* https://github.com/akseong/datagoboop

* https://github.com/ajrgodfrey/brailler

* https://www.desmos.com/accessibility

* https://www.highcharts.com/docs/accessibility/accessibility-module

* https://support.sas.com/software/products/graphics-accelerator/samples/index.html

* https://ukfinancialservicesinsights.deloitte.com/post/102gu0i/how-a-blind-data-scientist-writes-code

**Comment by jooyoungseo** [comment]
One more: I have just bumped into this great tool!

* https://papertohtml.org/

**Comment by LizHareDogs** [comment]
Thanks so much @jooyoungseo! This sounds like it will be great!￼

**Comment by jooyoungseo** [comment]
* https://medium.com/nightingale/writing-alt-text-for-data-visualization-2a218ef43f81
